### ISSUE TITLE
InvalidSignatureException 

### ISSUE THREAD

**Issue by nickbreen** [rjocoleman/syslog-cloudwatch-bridge#1]
Error messages on container statup

    InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. 

I've configured an IAM user with the access policy defined in the readme.

(On docker-cloud) the container stops immediately with these log messages:

    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.660645154Z` 2016/11/07 10:12:53 Starting syslog server on 0.0.0.0:514 
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.660726032Z 2016/11/07 10:12:53 Logging to group: wp-foobar 
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683301475Z 2016/11/07 10:12:53 InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. 
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683317196Z  
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683322591Z The Canonical String for this request should have been 
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683327143Z 'POST 
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683331661Z / 
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683335947Z  
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683340062Z content-length:83 
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683344395Z content-type:application/x-amz-json-1.1 
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683348872Z host:logs.ap-southeast-2.amazonaws.com 
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683353070Z x-amz-date:20161107T101253Z 
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683357403Z x-amz-target:Logs_20140328.CreateLogStream 
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683361505Z  
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683365623Z content-length;content-type;host;x-amz-date;x-amz-target 
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683369963Z ee30a5b88843eae75b1a43e1f588704a640483272c5a5bcb56aadea784a73ebf' 
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683374293Z  
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683378262Z The String-to-Sign should have been 
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683382529Z 'AWS4-HMAC-SHA256 
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683386592Z 20161107T101253Z 
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683390710Z 20161107/ap-southeast-2/logs/aws4_request 
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683394895Z 17e1e76a2e0e3cd91b726c638b8abb8c1246cbf5ad1a2bb4167ba548fa91bcbb' 
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683399081Z  
    [syslog-cloudwatch-bridge-1]2016-11-07T10:12:53.683403118Z 	status code: 400, request id: bf49f029-a4d2-11e6-8b29-752d0bded5f3

docker-cloud stackfile:

    syslog-cloudwatch-bridge:
      image: rjocoleman/syslog-cloudwatch-bridge
      environment:
        AWS_REGION: ap-southeast-2
        AWS_ACCESS_KEY_ID: REDACTED
        AWS_SECRET_ACCESS_KEY: REDACTED
        LOG_GROUP_NAME: REDACTED
      expose:
        - "514"
        - "514/udp"

**Comment by nickbreen** [comment]
Oddly, it works perfectly with docker-compose with the exact same YML file.

I suspect that there is something odd with the AWS EC2 instance role with docker-cloud.

**Comment by rjocoleman** [comment]
this is a pretty generic signing error.. do both machines have their clocks in sync?

**Comment by nickbreen** [comment]
Good call, I'll check.

**Comment by nickbreen** [comment]
Yes, it was timezone related!

Adding a volume for `/etc/timezone` has worked.

```
syslog-cloudwatch-bridge:
  image: rjocoleman/syslog-cloudwatch-bridge
  volumes:
    - /etc/timezone:/etc/timezone:ro
  environment:
    AWS_REGION: ap-southeast-2
    AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID: REDACTED
    AWS_SECRET_ACCESS_KEY: REDACTED
    LOG_GROUP_NAME: REDACTED
  expose:
    - "514"
    - "514/udp"
```

**Comment by rjocoleman** [comment]
thanks @nickbreen i'll add this to the README. it's probably a common issue!
