### ISSUE TITLE
Support for batching of log messages

### ISSUE THREAD

**Issue by guss77** [rjocoleman/syslog-cloudwatch-bridge#8]
Because the Cloudwatch Logs `PutLogEvents` API is throttled at 5 messages per second (https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html), it would be beneficial if multiple messages can be batched in a single API call.

For example, if in https://github.com/rjocoleman/syslog-cloudwatch-bridge/blob/4f65c5e96b5556a8823c0387818823c754fa464d/main.go#L61 instead of passing each message in the range to the send function, the entire range could be passed and that would allow more messages to be sent at once, increasing the performance of the bridge and reducing the likelihood of throttling.

**Comment by guss77** [comment]
Fixed in PR #9

**Comment by rjocoleman** [comment]
Closed by #9
